INSERT INTO films (titreFilm, genreFilm, budgetFilm, dureeFilm, paysorigineFilm)
VALUES
('Interstellar', 'Science-fiction', 165000000, 169, 'Royaume-Uni'),
('Dunkerque', 'Guerre', 100000000, 106, 'Royaume-Uni'),
('The Dark Knight : Le Chevalier noir', 'Super-héros', 185000000, 147, 'Royaume-Uni'),
('John Rambo', 'Action', 50000000, 91, 'État-Unis'),
('Projet X', 'Comédie', 12000000, 88, 'État-Unis'),
('Hannibal', 'Horreur', 87000000, 125, 'État-Unis'),
('Dragons', 'Animation', 165000000, 93, 'État-Unis'),
('Doctor Strange', 'Super-héros', 165000000, 147, 'État-Unis'),
('Invictus', 'Drame', 60000000, 134, 'État-Unis'),
('Indiana Jones et le Royaume du crâne de cristal', 'Aventure', 125000000, 123, 'État-Unis');

INSERT INTO personnages (nomPersonnage, prenomPersonnage, aliasPersonnage, lieuPersonnage, activitePersonnage, nemesisPersonnage, createurPersonnage, idFilm)
VALUES
('Cooper', 'Joseph', NULL, NULL, 'Ancien pilote de la NASA', NULL, NULL, 1),
('Brand', 'Amélia', NULL, NULL, 'Docteur', NULL, NULL, 1),
('Cooper', 'Murphy', NULL, NULL, 'Chercheuse scientifique', NULL, NULL, 1),
('Brand', 'John', NULL, NULL, 'Professeur', NULL, NULL, 1),
('Cooper', 'Tom', NULL, NULL, 'Agriculteur', NULL, NULL, 1),
('Cooper', 'Donald', NULL, NULL, NULL, NULL, NULL, 1),
(NULL, 'Tommy', NULL, 'Dunkerque', 'Soldat du CEB', 'Soldats allemands', NULL, 2),
(NULL, 'Peter', NULL, 'Dunkerque', 'Fils du capitaine du Moonstone', 'Soldats allemands', NULL, 2),
(NULL, 'Collins', NULL, 'Dunkerque', 'Pilote de la Royal Air Force', 'Soldats allemands', NULL, 2),
(NULL, 'Alex', NULL, 'Dunkerque', 'Soldat des Argyll & Sutherland Highlanders', 'Soldats allemands', NULL, 2),
(NULL, 'George', NULL, 'Dunkerque', "Membre d'équipage du Moonstone", 'Soldats allemands', NULL, 2),
(NULL, NULL, NULL, 'Dunkerque', 'Officier du CEB', 'Soldats allemands', NULL, 2),
('Wayne', 'Bruce','Batman', 'Gotham City', 'Propriétaire de Wayne Enterprises', 'Le Joker', '', 3),
(NULL, NULL,'Le Joker', 'Gotham City', 'Tueur en série', 'Batman', 'Bob Kane & Bill Finger', 3),
('Pennyworth', 'Alfred',NULL, 'Gotham City', 'Majordome', NULL, 'Bob Kane', 3),
('Gordon', 'Jim', NULL, 'Gotham City', 'Commissaire', 'Le Joker', 'Bob Kane & Bill Finger', 3),
('Dent', 'Harvey', 'Double-Face', 'Gotham City', 'Ancien procureur de district', 'Batman', 'Bob Kane & Bill Finger', 3),
('Dawes', 'Rachel', NULL, 'Gotham City', 'Ancien procureur général', NULL, 'David S. Goyer & Christopher Nolan', 3),
('Fox', 'Lucius', NULL, 'Gotham City', 'Directeur général de Wayne Enterprises', NULL, 'Len Wein & John Calnan',3),
('Crane', 'Jonathan', "L'Épouvantail", 'Gotham City', 'Docteur en psychologie', 'Batman','Bob Kane & Bill Finger', 3),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
();
